# Change these first
owner: JMousqueton # Your GitHub organization or username, where this repository lives
repo: uptime.ransomware.live # The name of this repository
user-agent: uptime.ransomware.live

sites:
  - name: ransomware.live - Main site
    url: https://www.ransomware.live
  - name: ransomware.live - Posts
    url: https://posts.ransomware.live
  - name: ransomware.live - Data
    url: https://data.ransomware.live
  - name: ransomware.live - Images
    url: https://images.ransomware.live
  - name: ransomware.live - Chat
    url: https://chat.ransomware.live
  - name: ransomware.live - API
    url: https://api.ransomware.live
  - name : Blog Julien Mousqueton
    url: https://julien.io
  - name : Cyber-News
    url: https://cyber-news.fr

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.ransomware.live
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/JMousqueton/uptime.ransomware.live/master/static/img/icon.svg
  name: Uptime Ransomware.live
  theme: light
  introTitle: "**Uptime**.ransomware.live monitor ransomware.live websites uptime"
  introMessage: This is status page which uses **real-time** data. No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title : Ransomware.live
      href: https://www.ransomware.live
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
