# Change these first
owner: jmousqueton # Your GitHub organization or username, where this repository lives
repo: uptime.ransomware.live # The name of this repository

sites:
  - name: Ransomware.live (site)
    url: https://www.ransomware.live
  - name: Ransomware.live (API-Pro)
    url: https://api-pro.ransomware.live/health
  - name: Ransomware.live (map)
    url: https://map.ransomware.live

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  themeUrl: https://static.ransomware.live/uptime.css
  cname: uptime.ransomware.live
  # baseUrl: /your-repo-name
  logoUrl: https://images.ransomware.live/ransomwarelive.svg
  name: Ransomware.live Status
  introTitle: "**Ransomware.live** status page"
  introMessage: "This page is powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: Ransomware.live
      href: https://www.ransomware.live

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
